import { ArrowLeft, Check, LockKeyhole, Plus, ShieldCheck } from "lucide-react";
import { useState } from "react";

type Mode = "home" | "adult" | "child";
type ChildChoice = "safe" | "not-yet" | undefined;

const CHILD_TITLES = [
  { name: "Paddington 2", image: "https://image.tmdb.org/t/p/w500/1OJ9vkD5xPt3skC6KguyXAgagRZ.jpg" },
  { name: "Spirited Away", image: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg" },
  { name: "The Iron Giant", image: "https://image.tmdb.org/t/p/w500/ct04FCFLPImNGSRnuTm5R7MmD0J.jpg" },
  { name: "Kiki’s Delivery Service", image: "https://image.tmdb.org/t/p/w500/Aufa4YdZIv4axM1QPyOfr7YfsFK.jpg" },
];

export function FamilySuite() {
  const [mode, setMode] = useState<Mode>("home");
  const [adultName, setAdultName] = useState("");
  const [adultPin, setAdultPin] = useState(false);
  const [childName, setChildName] = useState("");
  const [childChoices, setChildChoices] = useState<Record<string, ChildChoice>>({});
  const [childPin, setChildPin] = useState("");
  const [profiles, setProfiles] = useState([{ name: "Austin", kind: "Adult", pin: false }]);
  const addAdult = () => { if (!adultName.trim()) return; setProfiles((items) => [...items, { name: adultName.trim(), kind: "Adult", pin: adultPin }]); setAdultName(""); setAdultPin(false); setMode("home"); };
  const addChild = () => { if (!childName.trim() || childPin.length !== 4) return; setProfiles((items) => [...items, { name: childName.trim(), kind: "Child", pin: true }]); setChildName(""); setChildPin(""); setMode("home"); };

  if (mode === "adult") return <ProfileForm title="Add an adult" name={adultName} setName={setAdultName} optionalPin={adultPin} setOptionalPin={setAdultPin} onBack={() => setMode("home")} onSave={addAdult} />;
  if (mode === "child") return <ChildProfile name={childName} setName={setChildName} choices={childChoices} setChoices={setChildChoices} pin={childPin} setPin={setChildPin} onBack={() => setMode("home")} onSave={addChild} />;

  return <section className="mx-auto max-w-6xl px-5 py-14 md:px-10"><div className="flex items-end justify-between"><div><h1 className="font-display text-5xl font-semibold tracking-[-.07em]">Family</h1><p className="mt-3 max-w-lg text-white/58">Profiles, preferences, and the rules that make this home work for everyone.</p></div></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{profiles.map((profile) => <div key={profile.name} className="reelos-family-card rounded-[1.7rem] border border-white/10 p-6"><span className={`grid size-16 place-items-center rounded-full text-xl font-semibold ${profile.kind === "Child" ? "bg-[#5fd2c1] text-[#082421]" : "bg-[#b8c7ff] text-[#111426]"}`}>{profile.name[0]}</span><b className="mt-8 block text-xl">{profile.name}</b><span className="mt-1 block text-sm text-white/48">{profile.kind}{profile.pin ? " · PIN protected" : " · Open profile"}</span></div>)}<button onClick={() => setMode("adult")} className="reelos-family-card group rounded-[1.7rem] border border-dashed border-white/20 p-6 text-left"><span className="grid size-16 place-items-center rounded-full border border-dashed border-white/30 text-white/55"><Plus /></span><b className="mt-8 block text-xl">Add an adult</b><span className="mt-1 block text-sm text-white/48">Their own history and taste.</span></button><button onClick={() => setMode("child")} className="reelos-family-card rounded-[1.7rem] border border-white/10 bg-[linear-gradient(145deg,rgba(95,210,193,.16),rgba(50,84,135,.18))] p-6 text-left"><span className="grid size-16 place-items-center rounded-full bg-[#5fd2c1]/20 text-[#5fd2c1]"><ShieldCheck /></span><b className="mt-8 block text-xl">Add a child</b><span className="mt-1 block text-sm text-white/55">Train their own safe little cinema.</span></button></div></section>;
}

function ProfileForm({ title, name, setName, optionalPin, setOptionalPin, onBack, onSave }: { title: string; name: string; setName(value: string): void; optionalPin: boolean; setOptionalPin(value: boolean): void; onBack(): void; onSave(): void }) { return <section className="mx-auto max-w-2xl px-5 py-14 md:px-10"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm text-white/55 hover:text-white"><ArrowLeft className="size-4" />Family</button><h1 className="mt-10 font-display text-5xl font-semibold tracking-[-.07em]">{title}</h1><div className="mt-10 border-b border-white/25"><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Their name" className="w-full bg-transparent py-4 text-2xl outline-none placeholder:text-white/25" /></div><button onClick={() => setOptionalPin(!optionalPin)} className={`mt-8 flex w-full items-center justify-between rounded-[1.25rem] border p-5 text-left ${optionalPin ? "border-[#b8c7ff]/70 bg-white/8" : "border-white/10"}`}><span><b className="block">Protect this profile with a PIN</b><small className="mt-1 block text-sm text-white/50">Optional for adults. Keeps their history and taste private.</small></span><span className={`grid size-8 place-items-center rounded-full ${optionalPin ? "bg-[#b8c7ff] text-[#111426]" : "bg-white/10"}`}>{optionalPin && <Check className="size-4" />}</span></button><button disabled={!name.trim()} onClick={onSave} className="reelos-play mt-9 rounded-full bg-[#f0ba61] px-6 py-3.5 text-sm font-bold text-[#211507] disabled:opacity-35">Add profile</button></section>; }

function ChildProfile({ name, setName, choices, setChoices, pin, setPin, onBack, onSave }: { name: string; setName(value: string): void; choices: Record<string, ChildChoice>; setChoices(value: Record<string, ChildChoice>): void; pin: string; setPin(value: string): void; onBack(): void; onSave(): void }) { return <section className="mx-auto max-w-6xl px-5 py-14 md:px-10"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm text-white/55 hover:text-white"><ArrowLeft className="size-4" />Family</button><div className="mt-10 max-w-2xl"><h1 className="font-display text-5xl font-semibold tracking-[-.07em]">Make a safe little cinema.</h1><p className="mt-4 text-white/58">You teach ReelOS what feels right for this child. Nothing is decided by a rating alone.</p><div className="mt-8 border-b border-white/25"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Child’s name" className="w-full bg-transparent py-4 text-2xl outline-none placeholder:text-white/25" /></div></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{CHILD_TITLES.map((title) => <div key={title.name} className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[.035]"><img src={title.image} alt="" className="aspect-video w-full object-cover" /><div className="p-4"><b>{title.name}</b><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => setChoices({ ...choices, [title.name]: "safe" })} className={`rounded-full py-2 text-xs font-semibold ${choices[title.name] === "safe" ? "bg-[#5fd2c1] text-[#082421]" : "bg-white/8 text-white/65"}`}>Safe</button><button onClick={() => setChoices({ ...choices, [title.name]: "not-yet" })} className={`rounded-full py-2 text-xs font-semibold ${choices[title.name] === "not-yet" ? "bg-[#df8790] text-[#311014]" : "bg-white/8 text-white/65"}`}>Not yet</button></div></div></div>)}</div><div className="mt-12 max-w-xl rounded-[1.5rem] border border-white/10 bg-white/[.035] p-6"><div className="flex gap-3"><LockKeyhole className="mt-1 size-5 text-[#b8c7ff]" /><div><b>Kids need a code to leave.</b><p className="mt-2 text-sm leading-6 text-white/52">This child profile cannot enter adult profiles or change family rules without the family PIN.</p></div></div><input value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0, 4))} inputMode="numeric" placeholder="Create 4-digit family PIN" className="mt-6 w-full rounded-xl bg-black/20 px-4 py-3 text-lg tracking-[.3em] outline-none placeholder:tracking-normal placeholder:text-white/28" /></div><button disabled={!name.trim() || pin.length !== 4} onClick={onSave} className="reelos-play mt-9 rounded-full bg-[#f0ba61] px-6 py-3.5 text-sm font-bold text-[#211507] disabled:opacity-35">Create child profile</button></section>; }
