/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AmbianceRouteImport } from './routes/ambiance'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CalibrateRouteImport } from './routes/calibrate'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as FlickmatchRouteImport } from './routes/flickmatch'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PartyRouteImport } from './routes/party'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TvRouteImport } from './routes/tv'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as DiscoverMoviesRouteImport } from './routes/discover.movies'
import { Route as DiscoverShowsRouteImport } from './routes/discover.shows'
import { Route as EngineIdRouteImport } from './routes/engine.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as TitleIdRouteImport } from './routes/title.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbianceRoute = AmbianceRouteImport.update({
  id: '/ambiance',
  path: '/ambiance',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateRoute = CalibrateRouteImport.update({
  id: '/calibrate',
  path: '/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const FlickmatchRoute = FlickmatchRouteImport.update({
  id: '/flickmatch',
  path: '/flickmatch',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverMoviesRoute = DiscoverMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => DiscoverRoute,
} as any)
const DiscoverShowsRoute = DiscoverShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => DiscoverRoute,
} as any)
const EngineIdRoute = EngineIdRouteImport.update({
  id: '/engine/$id',
  path: '/engine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ambiance': typeof AmbianceRoute
  '/books': typeof BooksRoute
  '/calibrate': typeof CalibrateRoute
  '/companion': typeof CompanionRoute
  '/connect': typeof ConnectRoute
  '/dev': typeof DevRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/family': typeof FamilyRoute
  '/flickmatch': typeof FlickmatchRoute
  '/guide': typeof GuideRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tv': typeof TvRoute
  '/collection/$id': typeof CollectionIdRoute
  '/discover/movies': typeof DiscoverMoviesRoute
  '/discover/shows': typeof DiscoverShowsRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
  '/discover/': typeof DiscoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ambiance': typeof AmbianceRoute
  '/books': typeof BooksRoute
  '/calibrate': typeof CalibrateRoute
  '/companion': typeof CompanionRoute
  '/connect': typeof ConnectRoute
  '/dev': typeof DevRoute
  '/family': typeof FamilyRoute
  '/flickmatch': typeof FlickmatchRoute
  '/guide': typeof GuideRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tv': typeof TvRoute
  '/collection/$id': typeof CollectionIdRoute
  '/discover/movies': typeof DiscoverMoviesRoute
  '/discover/shows': typeof DiscoverShowsRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
  '/discover': typeof DiscoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ambiance': typeof AmbianceRoute
  '/books': typeof BooksRoute
  '/calibrate': typeof CalibrateRoute
  '/companion': typeof CompanionRoute
  '/connect': typeof ConnectRoute
  '/dev': typeof DevRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/family': typeof FamilyRoute
  '/flickmatch': typeof FlickmatchRoute
  '/guide': typeof GuideRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tv': typeof TvRoute
  '/collection/$id': typeof CollectionIdRoute
  '/discover/movies': typeof DiscoverMoviesRoute
  '/discover/shows': typeof DiscoverShowsRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
  '/discover/': typeof DiscoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ambiance'
    | '/books'
    | '/calibrate'
    | '/companion'
    | '/connect'
    | '/dev'
    | '/discover'
    | '/family'
    | '/flickmatch'
    | '/guide'
    | '/join'
    | '/library'
    | '/party'
    | '/profile'
    | '/requests'
    | '/settings'
    | '/tv'
    | '/collection/$id'
    | '/discover/movies'
    | '/discover/shows'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
    | '/discover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ambiance'
    | '/books'
    | '/calibrate'
    | '/companion'
    | '/connect'
    | '/dev'
    | '/family'
    | '/flickmatch'
    | '/guide'
    | '/join'
    | '/library'
    | '/party'
    | '/profile'
    | '/requests'
    | '/settings'
    | '/tv'
    | '/collection/$id'
    | '/discover/movies'
    | '/discover/shows'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
    | '/discover'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ambiance'
    | '/books'
    | '/calibrate'
    | '/companion'
    | '/connect'
    | '/dev'
    | '/discover'
    | '/family'
    | '/flickmatch'
    | '/guide'
    | '/join'
    | '/library'
    | '/party'
    | '/profile'
    | '/requests'
    | '/settings'
    | '/tv'
    | '/collection/$id'
    | '/discover/movies'
    | '/discover/shows'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
    | '/discover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AmbianceRoute: typeof AmbianceRoute
  BooksRoute: typeof BooksRoute
  CalibrateRoute: typeof CalibrateRoute
  CompanionRoute: typeof CompanionRoute
  ConnectRoute: typeof ConnectRoute
  DevRoute: typeof DevRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  FamilyRoute: typeof FamilyRoute
  FlickmatchRoute: typeof FlickmatchRoute
  GuideRoute: typeof GuideRoute
  JoinRoute: typeof JoinRoute
  LibraryRoute: typeof LibraryRoute
  PartyRoute: typeof PartyRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TvRoute: typeof TvRoute
  CollectionIdRoute: typeof CollectionIdRoute
  EngineIdRoute: typeof EngineIdRoute
  PersonIdRoute: typeof PersonIdRoute
  PlayIdRoute: typeof PlayIdRoute
  TitleIdRoute: typeof TitleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiance': {
      id: '/ambiance'
      path: '/ambiance'
      fullPath: '/ambiance'
      preLoaderRoute: typeof AmbianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate': {
      id: '/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof CalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flickmatch': {
      id: '/flickmatch'
      path: '/flickmatch'
      fullPath: '/flickmatch'
      preLoaderRoute: typeof FlickmatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/movies': {
      id: '/discover/movies'
      path: '/movies'
      fullPath: '/discover/movies'
      preLoaderRoute: typeof DiscoverMoviesRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/discover/shows': {
      id: '/discover/shows'
      path: '/shows'
      fullPath: '/discover/shows'
      preLoaderRoute: typeof DiscoverShowsRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/engine/$id': {
      id: '/engine/$id'
      path: '/engine/$id'
      fullPath: '/engine/$id'
      preLoaderRoute: typeof EngineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DiscoverRouteChildren {
  DiscoverMoviesRoute: typeof DiscoverMoviesRoute
  DiscoverShowsRoute: typeof DiscoverShowsRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverMoviesRoute: DiscoverMoviesRoute,
  DiscoverShowsRoute: DiscoverShowsRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AmbianceRoute: AmbianceRoute,
  BooksRoute: BooksRoute,
  CalibrateRoute: CalibrateRoute,
  CompanionRoute: CompanionRoute,
  ConnectRoute: ConnectRoute,
  DevRoute: DevRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  FamilyRoute: FamilyRoute,
  FlickmatchRoute: FlickmatchRoute,
  GuideRoute: GuideRoute,
  JoinRoute: JoinRoute,
  LibraryRoute: LibraryRoute,
  PartyRoute: PartyRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TvRoute: TvRoute,
  CollectionIdRoute: CollectionIdRoute,
  EngineIdRoute: EngineIdRoute,
  PersonIdRoute: PersonIdRoute,
  PlayIdRoute: PlayIdRoute,
  TitleIdRoute: TitleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
