/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as EngineIdRouteImport } from './routes/engine.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as TitleIdRouteImport } from './routes/title.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineIdRoute = EngineIdRouteImport.update({
  id: '/engine/$id',
  path: '/engine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/books': typeof BooksRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/collection/$id': typeof CollectionIdRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/books': typeof BooksRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/collection/$id': typeof CollectionIdRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/books': typeof BooksRoute
  '/connect': typeof ConnectRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/collection/$id': typeof CollectionIdRoute
  '/engine/$id': typeof EngineIdRoute
  '/person/$id': typeof PersonIdRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/books'
    | '/connect'
    | '/discover'
    | '/library'
    | '/requests'
    | '/settings'
    | '/collection/$id'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/books'
    | '/connect'
    | '/discover'
    | '/library'
    | '/requests'
    | '/settings'
    | '/collection/$id'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/books'
    | '/connect'
    | '/discover'
    | '/library'
    | '/requests'
    | '/settings'
    | '/collection/$id'
    | '/engine/$id'
    | '/person/$id'
    | '/play/$id'
    | '/settings/advanced'
    | '/title/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BooksRoute: typeof BooksRoute
  ConnectRoute: typeof ConnectRoute
  DiscoverRoute: typeof DiscoverRoute
  LibraryRoute: typeof LibraryRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  CollectionIdRoute: typeof CollectionIdRoute
  EngineIdRoute: typeof EngineIdRoute
  PersonIdRoute: typeof PersonIdRoute
  PlayIdRoute: typeof PlayIdRoute
  TitleIdRoute: typeof TitleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/$id': {
      id: '/engine/$id'
      path: '/engine/$id'
      fullPath: '/engine/$id'
      preLoaderRoute: typeof EngineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BooksRoute: BooksRoute,
  ConnectRoute: ConnectRoute,
  DiscoverRoute: DiscoverRoute,
  LibraryRoute: LibraryRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  CollectionIdRoute: CollectionIdRoute,
  EngineIdRoute: EngineIdRoute,
  PersonIdRoute: PersonIdRoute,
  PlayIdRoute: PlayIdRoute,
  TitleIdRoute: TitleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
